In [237]:
import numpy as np 
import numpy.linalg as LA
import math


In [262]:
A = np.array([
    [3,1,1],
    [-1,3,1]
])
# A = np.array([[3,2,2], [2,3,-2]])

In [308]:
def svd(A):
    V = np.dot(A.T, A)
    U = np.dot(A, A.T)
    uw, uv = LA.eig(U)
    vw, vv = LA.eig(V)
    S = list()
    for i,j in enumerate( range(len(vw)-1, 0, -1)):
        arr = np.zeros(len(vw))
        arr[i] = math.sqrt(vw[j])
        S.append(arr)
    print(f"S = {S}")
    print(f"U= {np.linalg.qr(uv)}")
    print(f"V= {vv}")
    return np.dot(np.dot(uv,S), vv)

In [309]:
svd(A)

S = [array([3.46410162, 0.        , 0.        ]), array([0.        , 3.16227766, 0.        ])]
U= (array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]]), array([[-1.,  0.],
       [ 0.,  1.]]))
V= [[ 1.82574186e-01 -8.94427191e-01 -4.08248290e-01]
 [ 3.65148372e-01  4.47213595e-01 -8.16496581e-01]
 [-9.12870929e-01  5.07702013e-16 -4.08248290e-01]]


array([[-0.36928299, -3.19089023,  0.82574186],
       [ 1.26371018, -1.19089023, -2.82574186]])

In [314]:
A = np.array([
    [1, 2, 1], 
    [0, 2, 0],
    [2, 3, 1],
    [1, 1, 0]
])
Q, R = LA.qr(A)

In [315]:
Q, R

(array([[-4.08248290e-01, -2.35702260e-01,  6.66666667e-01],
        [-0.00000000e+00, -9.42809042e-01, -3.33333333e-01],
        [-8.16496581e-01, -2.77555756e-17, -5.55111512e-17],
        [-4.08248290e-01,  2.35702260e-01, -6.66666667e-01]]),
 array([[-2.44948974, -3.67423461, -1.22474487],
        [ 0.        , -2.12132034, -0.23570226],
        [ 0.        ,  0.        ,  0.66666667]]))

In [316]:
math.sqrt(6)

2.449489742783178

In [365]:
def normalize(v):
    magnitue = LA.norm(v)
    return np.multiply(1/magnitue, v)

In [501]:
def gs(M):
    U = np.array([normalize(M[:,0])])
    for i in range(1, M.shape[1]):
        v = M[:,i]
        for u in U:
            v = np.subtract(v,  np.multiply(np.dot(u,v), u)) 
        U = np.append(U, [normalize(v)], axis=0)
    return U.T


In [504]:
M = np.array([
    [1, 2, 1], 
    [0, 2, 0],
    [2, 3, 1],
    [1, 1, 0]
])
gs(M)

array([[ 4.08248290e-01,  2.35702260e-01,  6.66666667e-01],
       [ 0.00000000e+00,  9.42809042e-01, -3.33333333e-01],
       [ 8.16496581e-01, -4.18691322e-16, -1.85037171e-16],
       [ 4.08248290e-01, -2.35702260e-01, -6.66666667e-01]])

In [506]:
x = 0.0 
y = 0.0
x is y

False

In [514]:
float(12321) is float(12321)

False